"""empty message

Revision ID: 52a73a1f4882
Revises: 504de573e4ea
Create Date: 2026-04-10 23:11:00.626184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a73a1f4882'
down_revision = '504de573e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('exchange_rate_date_key'), type_='unique')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('exchange_rate_date_key'), ['date'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('cash_shift', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
