"""empty message

Revision ID: 54c08442bfc1
Revises: f16739e48247
Create Date: 2026-04-01 23:24:23.937758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c08442bfc1'
down_revision = 'f16739e48247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_amount_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('open_amount_bs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_cash_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_cash_bs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_zelle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_pagomovil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_biopago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('close_punto', sa.Float(), nullable=True))
        batch_op.drop_column('close_amount')
        batch_op.drop_column('difference')
        batch_op.drop_column('open_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('difference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('close_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('close_punto')
        batch_op.drop_column('close_biopago')
        batch_op.drop_column('close_pagomovil')
        batch_op.drop_column('close_zelle')
        batch_op.drop_column('close_cash_bs')
        batch_op.drop_column('close_cash_usd')
        batch_op.drop_column('open_amount_bs')
        batch_op.drop_column('open_amount_usd')

    # ### end Alembic commands ###
